#!/bin/bash

set -e

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`
version="6.1.1"
url="https://github.com/project-mynt/mynt/releases/download"
tag="v6.1.1"

if [ "${platform}" == "linux" ]; then
    if [ "${arch}" == "x86_64" ]; then
        tarball_name="mynt-${version}-lin64.tar.gz"
    elif [ "${arch}" == "x86_32" ]; then
        tarball_name="mynt-${version}-lin32.tar.gz"
    fi
elif [ "${platform}" == "darwin" ]; then
    tarball_name="mynt-${version}-osx64.tar.gz"
else
    echo "Myntcoin binary distribution not available for platform and architecture"
    exit -1
fi

binary_url="${url}/${tag}/${tarball_name}"
shasums_url="${url}/${tag}/SHA256SUMS.asc"

download_myntd() {

    cd "${root_dir}/bin"

    echo "Downloading myntcoin: ${binary_url}"

    is_curl=true
    if hash curl 2>/dev/null; then
        curl --fail -I $binary_url >/dev/null 2>&1
    else
        is_curl=false
        wget --server-response --spider $binary_url >/dev/null 2>&1
    fi

    if test $? -eq 0; then
        if [ "${is_curl}" = true ]; then
            curl -L $binary_url > $tarball_name
            curl -L $shasums_url > SHA256SUMS.asc
        else
            wget $binary_url
            wget $shasums_url
        fi
        if test -e "${tarball_name}"; then
            echo "Unpacking myntcoin distribution"
            tar -xvzf $tarball_name
            if test $? -eq 0; then
                ln -sf "mynt-${version}/bin/myntd"
                return;
            fi
        fi
    fi
    echo "Myntoin binary distribution could not be downloaded"
    exit -1
}

verify_download() {
    echo "Verifying signatures of myntcoin download"
    gpg --verify "${root_dir}/bin/SHA256SUMS.asc"

    if hash shasum 2>/dev/null; then
        shasum_cmd="shasum -a 256"
    else
        shasum_cmd="sha256sum"
    fi

    download_sha=$(${shasum_cmd} "${root_dir}/bin/${tarball_name}" | awk '{print $1}')
    expected_sha=$(cat "${root_dir}/bin/SHA256SUMS.asc" | grep "${tarball_name}" | awk '{print $1}')
    echo "Checksum (download): ${download_sha}"
    echo "Checksum (verified): ${expected_sha}"
    if [ "${download_sha}" != "${expected_sha}" ]; then
        echo -e "\033[1;31mChecksums did NOT match!\033[0m\n"
        exit 1
    else
        echo -e "\033[1;32mChecksums matched!\033[0m\n"
    fi
}

download=1
verify=0

if [ "${SKIP_MYNTCOIN_DOWNLOAD}" = 1 ]; then
    download=0;
fi

if [ "${VERIFY_MYNTCOIN_DOWNLOAD}" = 1 ]; then
    verify=1;
fi

while [ -n "$1" ]; do
  param="$1"
  value="$2"

  case $param in
    --skip-myntcoin-download)
          download=0
          ;;
    --verify-myntcoin-download)
          verify=1
          ;;
  esac
  shift
done

if [ "${download}" = 1 ]; then
    download_myntd
fi

if [ "${verify}" = 1 ]; then
    verify_download
fi

exit 0
